<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerSaslClientTest" tests="3" skipped="0" failures="0" errors="0" timestamp="2020-01-15T02:09:30" hostname="localhost" time="0.002">
  <properties/>
  <testcase name="testWrapsExtensionsCallbackHandlingErrorInSaslExceptionInFirstClientMessage" classname="org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerSaslClientTest" time="0.002"/>
  <testcase name="testNoExtensionsDoesNotAttachAnythingToFirstClientMessage" classname="org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerSaslClientTest" time="0.0"/>
  <testcase name="testAttachesExtensionsToFirstClientMessage" classname="org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerSaslClientTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
