<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="kafka.api.SaslClientsWithInvalidCredentialsTest" tests="8" skipped="0" failures="0" errors="0" timestamp="2020-01-15T02:13:37" hostname="localhost" time="58.74">
  <properties/>
  <testcase name="testTransactionalProducerWithAuthenticationFailure" classname="kafka.api.SaslClientsWithInvalidCredentialsTest" time="6.989"/>
  <testcase name="testManualAssignmentConsumerWithAuthenticationFailure" classname="kafka.api.SaslClientsWithInvalidCredentialsTest" time="7.024"/>
  <testcase name="testConsumerGroupServiceWithAuthenticationSuccess" classname="kafka.api.SaslClientsWithInvalidCredentialsTest" time="7.531"/>
  <testcase name="testProducerWithAuthenticationFailure" classname="kafka.api.SaslClientsWithInvalidCredentialsTest" time="7.034"/>
  <testcase name="testConsumerGroupServiceWithAuthenticationFailure" classname="kafka.api.SaslClientsWithInvalidCredentialsTest" time="7.269"/>
  <testcase name="testManualAssignmentConsumerWithAutoCommitDisabledWithAuthenticationFailure" classname="kafka.api.SaslClientsWithInvalidCredentialsTest" time="6.851"/>
  <testcase name="testKafkaAdminClientWithAuthenticationFailure" classname="kafka.api.SaslClientsWithInvalidCredentialsTest" time="7.994"/>
  <testcase name="testConsumerWithAuthenticationFailure" classname="kafka.api.SaslClientsWithInvalidCredentialsTest" time="8.048"/>
  <system-out><![CDATA[Completed updating config for entity: user-principal 'scram-admin'.
[2020-01-15 10:13:39,604] ERROR [Producer clientId=producer-txclient-1, transactionalId=txclient-1] Connection to node -1 (localhost/127.0.0.1:58763) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient:745)
Completed updating config for entity: user-principal 'scram-user2'.
Completed updating config for entity: user-principal 'scram-admin'.
[2020-01-15 10:13:46,709] ERROR [Consumer clientId=consumer-group-4, groupId=group] Connection to node -1 (localhost/127.0.0.1:58892) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient:745)
[2020-01-15 10:13:46,819] ERROR [Consumer clientId=consumer-group-4, groupId=group] Connection to node -1 (localhost/127.0.0.1:58892) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient:745)
Completed updating config for entity: user-principal 'scram-user2'.
Completed updating config for entity: user-principal 'scram-admin'.
Completed updating config for entity: user-principal 'scram-user2'.
Completed updating config for entity: user-principal 'scram-admin'.
[2020-01-15 10:14:00,132] ERROR [Producer clientId=producer-3] Connection to node -1 (localhost/127.0.0.1:59226) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient:745)
[2020-01-15 10:14:00,238] ERROR [Producer clientId=producer-3] Connection to node -1 (localhost/127.0.0.1:59226) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient:745)
Completed updating config for entity: user-principal 'scram-user2'.
Completed updating config for entity: user-principal 'scram-admin'.
[2020-01-15 10:14:07,902] ERROR [AdminClient clientId=adminclient-7] Connection to node -1 (localhost/127.0.0.1:59337) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient:745)
Completed updating config for entity: user-principal 'scram-admin'.
[2020-01-15 10:14:14,943] ERROR [Consumer clientId=consumer-group-7, groupId=group] Connection to node -1 (localhost/127.0.0.1:59494) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient:745)
[2020-01-15 10:14:15,051] ERROR [Consumer clientId=consumer-group-7, groupId=group] Connection to node -1 (localhost/127.0.0.1:59494) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient:745)
Completed updating config for entity: user-principal 'scram-user2'.
Completed updating config for entity: user-principal 'scram-admin'.
[2020-01-15 10:14:22,151] ERROR [AdminClient clientId=adminclient-8] Connection to node -1 (localhost/127.0.0.1:59630) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient:745)
Completed updating config for entity: user-principal 'scram-user2'.
Completed updating config for entity: user-principal 'scram-admin'.
[2020-01-15 10:14:30,303] ERROR [Consumer clientId=consumer-group-8, groupId=group] Connection to node -1 (localhost/127.0.0.1:59859) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient:745)
[2020-01-15 10:14:30,512] ERROR [Consumer clientId=consumer-group-8, groupId=group] Connection to node -1 (localhost/127.0.0.1:59859) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-256 (org.apache.kafka.clients.NetworkClient:745)
Completed updating config for entity: user-principal 'scram-user2'.
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
